### ISSUE TITLE
Obtaining UPDRS using only KTOH-LH accelerometer data

### ISSUE THREAD

**Issue by j1moreno** [pdkit/pdkit#98]
Hello,
I am new to this and don't have much background info, so I apologize in advance if any part of this question is obvious.

I am having trouble figuring out how to get from accelerometer data to UPDRS score.
I have gone through the examples, which work, but I get errors when using my own data as input.

I am able to create a Test Result Set using accelerometer data, although I have noticed that it doesn't create all the columns included in the sample data. I create the UPDRS object using this Test Result Set as input; then when I attempt to use the score function using a row from the same Test Result Set (as shown in the example), I get the following error message:

 Traceback (most recent call last):
  File "tester.py", line 33, in <module>
    score = updrs.score(row)
  File "C:\Users\morenj3\AppData\Local\Programs\Python\Python37\lib\site-packages\pdkit\updrs.py", line 292, in score
    c, sd = self.__get_centroids_sd(obs)
TypeError: cannot unpack non-iterable NoneType object

It seems like UPDRS scoring will only work when measurement data containing all fields (e.g. OT, TT, PS, LA, PTOTH, KTOH, RTA) is given; is this correct?

My goal was to take accelerometer data from left/right hand tremor, and generate UPDRS score from it. Is this possible?

I apologize if this is not the correct place to ask this question, I wasn't sure where else to reach out. 

Any help would be greatly appreciated!

**Comment by gkroussos** [comment]
This is indeed not the place to ask questions about how to use the toolkit. You can use hello@updrs.net for that as indicated PDkit website. 

We will respond to your email directly when you do but in the meantime the problem is ingesting your data i.e. as you say  "I get errors when using my own data as input". Unless the data is correctly ingested, the pipeline will not work. There are descriptions of supported file formats in the data directory.
